
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	}
};


