#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/brandyn/fpga-image-registration/edk_project/blah.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /home/brandyn/Xilinx10.1i/EDK
NON_CYG_XILINX_EDK_DIR = /home/brandyn/Xilinx10.1i/EDK

SYSTEM = blah

MHSFILE = blah.mhs

MSSFILE = blah.mss

FPGA_ARCH = virtex5

DEVICE = xc5vsx50tff1136-1

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp /home/brandyn/fpga-image-registration/edk_user_repository/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error no

REGISTRATION_TEST_OUTPUT_DIR = registration_test
REGISTRATION_TEST_OUTPUT = $(REGISTRATION_TEST_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(REGISTRATION_TEST_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(REGISTRATION_TEST_OUTPUT) 

ALL_USER_ELF_FILES = $(REGISTRATION_TEST_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = registration_test_programclean 

CORE_STATE_DEVELOPMENT_FILES = /home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/netlist/div1.ngc \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/proc_common_pkg.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/ipif_pkg.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_muxcy.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/or_gate128.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/family_support.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/pselect_f.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v2_00_a/hdl/vhdl/counter_f.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plb_address_decoder.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plb_slave_attachment.vhd \
/home/brandyn/Xilinx10.1i/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_00_a/hdl/vhdl/plbv46_slave_single.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/registration_core.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/affine_coord_transform.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/compute_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/convert_2d_to_1d_coord.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/conv_pixel_ordering.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/demo_low_level_tld.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/demo_low_level.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/div1_test.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/div1.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/fetch_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/gauss_elim.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/i2c_core.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/i2c_video_programmer.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/image_display_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/image_store_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/img1_compute_mem_addr.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/make_a_b_matrices.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/make_affine_homography.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/mem_addr_selector.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/memory_dump.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/pipeline_bit_buffer.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/pipeline_buffer.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/pixel_buffer_3x3.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/pixel_memory_controller.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/registration_controller.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/registration_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/right_shifter.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/signed_norm_mult.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/smooth_address_selector.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/smooth_conv_3x3.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/smooth_stage.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/sum_a_b_matrices.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/unscale_h_matrix.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/vga_timing_decode.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/vga_timing_generator.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/zbt_controller.vhd \
/home/brandyn/fpga-image-registration/edk_user_repository/MyProcessorIPLib/pcores/registration_core_v1_00_a/hdl/vhdl/compose_h_matrix.vhd

WRAPPER_NGC_FILES = implementation/registration_core_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/debug_module_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/blah.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION REGISTRATION_TEST
#################################################################

REGISTRATION_TEST_SOURCES = /home/brandyn/Xilinx10.1i/edk_user_repository/MyProcessorIPLib/drivers/registration_core_v1_00_a/src/registration_core.c 

REGISTRATION_TEST_HEADERS = /home/brandyn/Xilinx10.1i/edk_user_repository/MyProcessorIPLib/drivers/registration_core_v1_00_a/src/registration_core.h 

REGISTRATION_TEST_CC = mb-gcc
REGISTRATION_TEST_CC_SIZE = mb-size
REGISTRATION_TEST_CC_OPT = -Os
REGISTRATION_TEST_CFLAGS = 
REGISTRATION_TEST_CC_SEARCH = # -B
REGISTRATION_TEST_LIBPATH = -L./microblaze_0/lib/ # -L
REGISTRATION_TEST_INCLUDES = -I./microblaze_0/include/  -I/home/brandyn/Xilinx10.1i/edk_user_repository/MyProcessorIPLib/drivers/registration_core_v1_00_a/src/ # -I
REGISTRATION_TEST_LFLAGS = # -l
REGISTRATION_TEST_LINKER_SCRIPT = registration_test/registration_test_linker_script.ld
REGISTRATION_TEST_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(REGISTRATION_TEST_LINKER_SCRIPT) 
REGISTRATION_TEST_CC_DEBUG_FLAG = # -[g|gstabs]
REGISTRATION_TEST_CC_PROFILE_FLAG = # -pg
REGISTRATION_TEST_CC_GLOBPTR_FLAG= # -mxl-gp-opt
REGISTRATION_TEST_MODE = executable
REGISTRATION_TEST_LIBG_OPT = -$(REGISTRATION_TEST_MODE) microblaze_0
REGISTRATION_TEST_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mxl-pattern-compare -mcpu=v7.10.d 
REGISTRATION_TEST_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
REGISTRATION_TEST_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
REGISTRATION_TEST_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
REGISTRATION_TEST_OTHER_CC_FLAGS= $(REGISTRATION_TEST_CC_GLOBPTR_FLAG)  \
                  $(REGISTRATION_TEST_CC_START_ADDR_FLAG) $(REGISTRATION_TEST_CC_STACK_SIZE_FLAG) $(REGISTRATION_TEST_CC_HEAP_SIZE_FLAG)  \
                  $(REGISTRATION_TEST_CC_INFERRED_FLAGS)  \
                  $(REGISTRATION_TEST_LINKER_SCRIPT_FLAG) $(REGISTRATION_TEST_CC_DEBUG_FLAG) $(REGISTRATION_TEST_CC_PROFILE_FLAG) 
